//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ibn_Sina_Diagnostic_Center.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrTable
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string About { get; set; }
        public string AppointmentDetails { get; set; }
        public string Chamber_details { get; set; }
    }
}
